### ISSUE TITLE
🐛 Setting project_path causes "Setup Project" to fail

### ISSUE THREAD

**Issue by abegehr** [w9jds/setup-firebase#1]
This is my GH action yml file:

```yaml
name: Deploy to Firebase on merge
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: w9jds/setup-firebase@v1.0.0
        with:
          tools-version: 12.3.1
          gcp_sa_key: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_WINSIDER_C894D }}"
          project_path: firebase
      - run: firebase deploy --except hosting
        working-directory: firebase
```

When I run it by pushing to main, the Setup Project sets fails with an error:

```txt
Error: Failed to setup firebase with error Error: Unable to locate executable file: cd. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
```

When I remove `project_path` and run only with `working-directory: firebase` on the `firebase deploy` step, it works as expected. I have also tried with `project_path` and without `working-directory`, which also fails on "Setup Project".
Is the `project_path` even necessary for setup-firebase, since it should just setup firebase-tools but the deploying in handled afterwards?
